apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-dev
spec:
  selector:
    matchLabels:
      app: app-dev
  replicas: 3 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
      - name: app-dev
        image: kserge2001/dev1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
